### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by gabrielmocanu**
Add extra information for running the application on XEN environment

Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

### CODE REVIEW

**Comment by razvand** [comment]
@gabrielmocanu , update the first line of the commit message to make it more descriptive. Say "Update README with details on running on Xen".

**Comment by gabrielmocanu** [comment]
@razvand  Done.

**Review by StefanJum — APPROVED** [review]
Looks good.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by razvand — APPROVED** [review]
Everything works OK :+1: 

Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Pull request closed without merging**
